<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>



</body>

<script>
    // // <!-- Create a new Promise object -->

    // let p1 = new Promise((resolve, reject) => {
    //     // Set a timeout of 2 seconds
    //     setTimeout(() => {
    //         console.log("Resolve after 2 seconds");
    //         // Resolve the promise with a value of 190
    //         resolve(190);
    //     }, 2000);
    // });


    // // Use the then() method to handle the resolved value of p1
    // p1.then((value) => {
    //     console.log(value);
    //     // Create a new Promise object
    //     let p2 = new Promise((resolve, reject) => {
    //         // Resolve the promise with a value of 'Promise2'
    //         resolve('Promise2');
    //         // return resolve;
    //     });
    //     // Return p2 to chain another then() method
    //     return p2;
    // })

    //     .then((value) => {
    //         console.log("we are Done");
    //         // Return 2 to chain another then() method
    //         return 2;
    //     })
    //     .then((value) => {
    //         console.log("now we are pakka done");
    //     });


    //load script fnunction using promises

    const loadscript = (src) => {
        return new Promise((resolve, reject) => {
            let script = document.createElement("script");
            script.type = "text/javascript";
            script.src = src;
            document.body.appendChild(script);
            script.onload = () => {
                resolve("script has been loaded sir");
            };

            script.onerror = () => { reject(0); };
        });
    };


    let p5 = loadscript("http://127.0.0.1:5500/JS%20Recap/Chapter_9/index5.html");
    p5.then((value) => {
        console.log(value);
        console.log('yess')
        return loadscript;
    })
        .then((value) => {
            console.log('gand mara');
        })
        .catch((error) => {
            console.log("Sory we cant load")
        })


        

</script>

</html>


<!-- 

// Imagine you have a function that returns a promise


//creation of function which is async
// and will return a promise resolve and reject
// if it is true then resolve 
// else reject 

/* 
using then we can operate on the values 

like after resolve print result 
if also works like a function 
same goes for error catch and throw 
*/

function fakeAsyncOperation() {
    return new Promise((resolve, reject) => {
        // Simulate an asynchronous operation
        setTimeout(() => {
            // Simulate a successful operation
            const success = true;
            if (success) {
                // Resolve the promise if the operation succeeds
                resolve("Operation completed successfully!");
            } else {
                // Reject the promise if the operation fails
                reject(new Error("Operation failed!"));
            }
        }, 2000); // Simulating a delay of 2 seconds
    });
}

// Now, you can use this function to perform an asynchronous operation
console.log("Starting operation...");
fakeAsyncOperation()
    .then(result => {
        // This block will execute if the promise is resolved (operation succeeds)
        console.log("Promise resolved:", result);
    })
    .catch(error => {
        // This block will execute if the promise is rejected (operation fails)
        console.error("Promise rejected:", error.message);
    });
console.log("Operation initiated!"); -->
